### ISSUE TITLE
MCH Stores>Add receipts/issues/returns/stockouts/equipment>Input invalid details in the fields>Save: the system displays an error message “Ajax error. Internal server error”. 

### ISSUE THREAD

**Issue by pwanjiru** [bespokeinteractive/mchapp#122]
Add receipts/issues/returns/stockouts/equipment>Input invalid details in the fields>Save: the system displays an error message “Ajax error. Internal server error”. 

Suggestion:
Refine the error message to reflect and alert on the input that has been wrongly entered.

**Comment by stansL** [comment]
Fixed

**Comment by pwanjiru** [comment]
fixed and tested
