### ISSUE TITLE
MCH Stores: Click on view button at the end of each item within MCH stores: the system displays an error “org.openmrs.ui.framework.UiFrameworkException: viewProvider mchapp does not have a view named storesReceipts”. 

### ISSUE THREAD

**Issue by pwanjiru** [bespokeinteractive/mchapp#125]
Click on view button at the end of each item within MCH stores: the system displays an error “org.openmrs.ui.framework.UiFrameworkException: viewProvider mchapp does not have a view named storesReceipts”. 

Suggestion: 
Allow viewing of individual item details on clicking this button.

**Comment by stansL** [comment]
Fixed

**Comment by pwanjiru** [comment]
has been fixed and tested
