### ISSUE TITLE
MCH Stores>Add issue/returns/stockouts: The expiry date displays “object-object” instead of the expiry date of the drug being issued. 

### ISSUE THREAD

**Issue by pwanjiru** [bespokeinteractive/mchapp#126]
The expiry date displays “object-object” instead of the expiry date of the drug being issued. 

Suggestion: 
display expiry date of drug issue.

**Comment by daugmaud** [comment]
This issue has been resolved. You can test and close this issue

**Comment by pwanjiru** [comment]
This has been fixed and tested
