### ISSUE TITLE
MCH Stores>Add equipment: Add equipment without selecting equipment type: System allows adding of an equipment without selecting an equipment type. 

### ISSUE THREAD

**Issue by pwanjiru** [bespokeinteractive/mchapp#128]
Add equipment without selecting equipment type: System allows adding of an equipment without selecting an equipment type. 

Suggestion: 
-Equipment type is needed for the reports MOH 710 section B thus must be made mandatory for one to select.

**Comment by daugmaud** [comment]
This issue has been addressed and fixed

**Comment by pwanjiru** [comment]
Fixed and tested
