### ISSUE TITLE
MCH Stores> Stock outs: Once we receive new stock for an item in stock outs, cancel out the item in stock outs to indicate new stock received

### ISSUE THREAD

**Issue by pwanjiru** [bespokeinteractive/mchapp#155]
MCH Stores> Stock outs: Once we receive new stock for an item in stock outs, cancel out the item in stock outs to indicate new stock received

Task
--------
-Cancel out or grey out an item in stock outs once new stock has been received for the same item.

**Comment by daugmaud** [comment]
This has been done. Test and close

**Comment by pwanjiru** [comment]
Tested and verified
