### ISSUE TITLE
MCH Stores: reworking of issue stock to MCH clinic and immunization commodities used

### ISSUE THREAD

**Issue by pwanjiru** [bespokeinteractive/mchapp#157]
MCH Stores: reworking of issue stock to MCH clinic and immunization commodities used

**Comment by daugmaud** [comment]
Kindly describe this further, the task isn't clear

**Comment by pwanjiru** [comment]
Task
-------
This is to encompass the following; which could be made as drop-down menus for the user to select whom they're issuing to:
-Issue to Community Health Worker (CHEW)
-Issue to Peripheral facility
-Issue to MCH stores

For issues made to Community Health worker, the system should allow them to make returns as this is done every day back to the facility. This should also add back to our drug stock.

**Comment by pwanjiru** [comment]
has been fixed and tested
