### ISSUE TITLE
MCH stores: when the attribute changes in drug inventory, the changes do not reflect in the MCH stores drug stock page

### ISSUE THREAD

**Issue by pwanjiru** [bespokeinteractive/mchapp#162]
MCH stores: when the attribute changes in drug inventory, the changes do not reflect in the MCH stores drug stock page

Task
-------------
-Ensure that attribute edited in drug inventory (in admin>manage drug) is also reflected in the MCH stores page in the attribute column

**Comment by daugmaud** [comment]
You can test and close this.

**Comment by pwanjiru** [comment]
Issue still recurring

**Comment by pwanjiru** [comment]
Has been fixed and tested
